export const SHADER_PRESETS = Object.freeze({
  'paper-texture': [
    {
      name: 'Default',
      params: {
        fit: 'cover',
        scale: 0.6,
        rotation: 0,
        offsetX: 0,
        offsetY: 0,
        originX: 0.5,
        originY: 0.5,
        worldWidth: 0,
        worldHeight: 0,
        speed: 0,
        frame: 0,
        colorFront: '#9fadbc',
        colorBack: '#ffffff',
        contrast: 0.3,
        roughness: 0.4,
        fiber: 0.3,
        fiberSize: 0.2,
        crumples: 0.3,
        crumpleSize: 0.35,
        folds: 0.65,
        foldCount: 5,
        fade: 0,
        drops: 0.2,
        seed: 5.8,
      },
    },
  ],
  'fluted-glass': [
    {
      name: 'Default',
      params: {
        fit: 'cover',
        scale: 1,
        rotation: 0,
        offsetX: 0,
        offsetY: 0,
        originX: 0.5,
        originY: 0.5,
        worldWidth: 0,
        worldHeight: 0,
        speed: 0,
        frame: 0,
        colorBack: '#00000000',
        colorShadow: '#000000',
        colorHighlight: '#ffffff',
        shadows: 0.25,
        size: 0.5,
        angle: 0,
        distortionShape: 'prism',
        highlights: 0.1,
        shape: 'lines',
        distortion: 0.5,
        shift: 0,
        blur: 0,
        edges: 0.25,
        stretch: 0,
        margin: 0,
        marginLeft: 0,
        marginRight: 0,
        marginTop: 0,
        marginBottom: 0,
        grainMixer: 0,
        grainOverlay: 0,
      },
    },
    {
      name: 'Waves',
      params: {
        fit: 'cover',
        scale: 1.2,
        rotation: 0,
        offsetX: 0,
        offsetY: 0,
        originX: 0.5,
        originY: 0.5,
        worldWidth: 0,
        worldHeight: 0,
        speed: 0,
        frame: 0,
        colorBack: '#00000000',
        colorShadow: '#000000',
        colorHighlight: '#ffffff',
        shadows: 0,
        size: 0.9,
        angle: 0,
        distortionShape: 'contour',
        highlights: 0,
        shape: 'wave',
        distortion: 0.5,
        shift: 0,
        blur: 0.1,
        edges: 0.5,
        stretch: 1,
        margin: 0,
        marginLeft: 0,
        marginRight: 0,
        marginTop: 0,
        marginBottom: 0,
        grainMixer: 0,
        grainOverlay: 0.05,
      },
    },
  ],
  water: [
    {
      name: 'Default',
      params: {
        fit: 'contain',
        scale: 0.8,
        rotation: 0,
        offsetX: 0,
        offsetY: 0,
        originX: 0.5,
        originY: 0.5,
        worldWidth: 0,
        worldHeight: 0,
        speed: 1,
        frame: 0,
        colorBack: '#909090',
        colorHighlight: '#ffffff',
        highlights: 0.07,
        layering: 0.5,
        edges: 0.8,
        waves: 0.3,
        caustic: 0.1,
        size: 1,
      },
    },
    {
      name: 'Streaming',
      params: {
        fit: 'contain',
        scale: 0.4,
        rotation: 0,
        offsetX: 0,
        offsetY: 0,
        originX: 0.5,
        originY: 0.5,
        worldWidth: 0,
        worldHeight: 0,
        speed: 2,
        frame: 0,
        colorBack: '#909090',
        colorHighlight: '#ffffff',
        highlights: 0,
        layering: 0,
        edges: 0,
        waves: 0.5,
        caustic: 0,
        size: 0.5,
      },
    },
  ],
  'image-dithering': [
    {
      name: 'Natural',
      params: {
        fit: 'cover',
        scale: 1,
        rotation: 0,
        offsetX: 0,
        offsetY: 0,
        originX: 0.5,
        originY: 0.5,
        worldWidth: 0,
        worldHeight: 0,
        speed: 0,
        frame: 0,
        colorFront: '#ffffff',
        colorBack: '#000000',
        colorHighlight: '#ffffff',
        type: '8x8',
        size: 2,
        colorSteps: 5,
        originalColors: true,
        inverted: false,
      },
    },
  ],
  'halftone-dots': [
    {
      name: 'Mosaic',
      params: {
        fit: 'cover',
        scale: 1,
        rotation: 0,
        offsetX: 0,
        offsetY: 0,
        originX: 0.5,
        originY: 0.5,
        worldWidth: 0,
        worldHeight: 0,
        speed: 0,
        frame: 0,
        colorBack: '#000000',
        colorFront: '#b2aeae',
        size: 0.6,
        radius: 2,
        contrast: 0.01,
        originalColors: true,
        inverted: false,
        grainMixer: 0,
        grainOverlay: 0,
        grainSize: 0.5,
        grid: 'hex',
        type: 'classic',
      },
    },
  ],
  'halftone-cmyk': [
    {
      name: 'Default',
      params: {
        fit: 'cover',
        scale: 1,
        rotation: 0,
        offsetX: 0,
        offsetY: 0,
        originX: 0.5,
        originY: 0.5,
        worldWidth: 0,
        worldHeight: 0,
        speed: 0,
        frame: 0,
        colorBack: '#fbfaf5',
        colorC: '#00b4ff',
        colorM: '#fc519f',
        colorY: '#ffd800',
        colorK: '#231f20',
        size: 0.2,
        contrast: 1,
        softness: 1,
        grainSize: 0.5,
        grainMixer: 0,
        grainOverlay: 0,
        gridNoise: 0.2,
        floodC: 0.15,
        floodM: 0,
        floodY: 0,
        floodK: 0,
        gainC: 0.3,
        gainM: 0,
        gainY: 0.2,
        gainK: 0,
        type: 'ink',
      },
    },
  ],
});
